shellEmulator: true

trustPolicy: no-downgrade

packages:
  - sdks/*
  - packages/*

overrides:
  '@typescript-eslint/eslint-plugin': 8.53.0
  ts-api-utils: 2.4.0

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
